[package]
name = "alerion_datamodel"
version = "0.1.0"
edition = "2021"

[dependencies]
bytestring = "1.3.1"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
smallvec = { version = "1.13.2", features = ["serde"] }
uuid = { version = "1.8.0", features = ["serde"] }
