[package]
name = "alerion_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
alerion_core = { version = "0.1.0", path = "../alerion_core" }
anyhow = "1.0.82"
tokio = { version = "1.37.0", features = ["rt", "macros"] }
